module.exports = {
    is_array: require('./is_array'),
    is_arrayLike: require('./is_arrayLike'),
    is_boolean: require('./is_boolean'),
    is_date: require('./is_date'),
    is_defined: require('./is_defined'),
    is_function: require('./is_function'),
    is_integer: require('./is_integer'),
    is_json: require('./is_json'),
    is_nan: require('./is_nan'),
    is_null: require('./is_null'),
    is_number: require('./is_number'),
    is_object: require('./is_object'),
    is_regexp: require('./is_regexp'),
    is_string: require('./is_string'),
    is_symbol: require('./is_symbol'),
    is_undefined: require('./is_undefined'),
};
